<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHHLm1Rz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHHLm1Rz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHHLm1Rz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHHLm1Rz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHHLm1Rz\App_KernelDevDebugContainer([
    'container.build_hash' => 'HHLm1Rz',
    'container.build_id' => 'eee22905',
    'container.build_time' => 1707313979,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHHLm1Rz');
